function [wmat] = gal2wmat(file,standardize)
% PURPOSE: convert .gal document generated by GeoDa into spatial weight
% matrix that could be used in matlab.
%---------------------------------------------------
% USAGE: gal2wmat(file,standardize)
% Where: file = file name of .gal document.
%        standardize  = convert spatial weight matrix into standardized
%        matrix or not. when standardize ~= 1, do not convert.
%        W          = spatial weights matrix used to estimate model
%---------------------------------------------------
if nargin ~= 2
    if nargin == 1
       standardize = 0;
    else
error('Wrong # of arguments to gal2wmat');
    end
end;

fidd = fopen(file,'r');
row=0;
while ~feof(fidd) 
    [~]=fgets(fidd); 
    row=row+1; 
end
fclose(fidd);
% Read .gal document by rows.
fid = fopen(file,'r');
ww=zeros(row);
for i=1:row
t=fgetl(fid);
rownum=str2num(t);
s=row-max(size(rownum));
ss=zeros(1,s);
tttt= [rownum ss];
ww(i,:)=ww(i,:) + tttt;
end
fclose(fid);

for ii=1:row
    if sum(ww(:,ii)) > 0
        m=ii;
    end
end

www=ww(2:row,1:m);
 % Convert sparse matrix to matrix.
wmatt = size(www);
nn=max(wmatt)/2;
wmattt=zeros(nn,nn);
   for k=1:nn
    l=2*k-1;
    mz=2*k;
    n=www(l,2);
     if n > 0
       for ii = 1:n 
        jj = www(mz,ii);
        kk = www(l,1);
        wmattt(kk,jj) = 1;
        wmattt(jj,kk) = 1;
       end 
     end 
   end
     % generate standardized spatial weight matrix.
   if standardize ~= 1
       wmat = wmattt;
   else 
   wmat=zeros(nn);
     for iii=1:nn
         for kkk=1:nn
            if sum(wmattt(iii,:)) > 0
   wmat(iii,kkk) = wmattt(iii,kkk)/sum(wmattt(iii,:));
            end
         end
     end
   end
end













